--DefineHuPai
local m = {}
m.huTpye = {
	HU_PINGHU = 1,				    --平胡
	HU_ZIMO = 2,				    --自摸
	--HU_QIANGGANGHU = 3,		    --抢扛胡
	HU_MENQING = 4,				    --门清
	HU_PIAOHU = 5,				    --飘胡
	HU_QIDUI = 6,				    --七对
	HU_QIANGMINGGANGHU = 7,		    --抢明扛胡
	HU_MOBAO = 8,				    --摸宝	听牌后有效, 冲宝
	--HU_LIANZHUANG = 11,		    --连庄
	HU_DIANPAO = 12,			    --点炮
	HU_JIEPAO = 13,				    --接炮
	HU_LUXURYQIDUI = 14,		    --豪华七对
	HU_LUXURYQIDUI_SHUANG = 15,	    --双豪华七对
	HU_ZHIZUNQIDUI = 16,		    --至尊豪华七对
	HU_JIAHU = 18,				    --夹胡
	HU_CHONGBAO = 20,			    --冲宝 听牌后有效
	HU_TINGPAI = 22,			    --可听牌
	HU_ANGANG = 23,                 --暗杠
	HU_MGANG = 24,                  --明杠
	HU_SPECIAL_MD = 27,             --明大蛋
	HU_SPECIAL_AD = 28,             --暗大蛋
	HU_WIN_KAIPAIZHA=29,            --开牌炸
	HU_SHUNBAOHU = 30,              --选择顺宝胡
	HU_DIANPAO_X2=150,			    --点炮x2

	HU_XIAOHU = 1,				    --小胡(胡牌分)--与小胡 一样
	--HU_ZIMO=7,				    --自摸
	--HU_GANGSHANGKAIHUA=8,		    --杠上开花
	HU_GANGSHANGPAO=9,			    --杠上炮
	HU_HAIDILAO=10,				    --海底捞
	HU_HAIDIPAO=11,				    --海底炮
	--HU_QIANGGANGHU=12,		    --抢扛胡
	HU_QISHOUFOURLAN=13,		    --起手四个赖子
	--HU_MENQING=14,			    --门清

	HU_SANYUANPAIONE=15,		    --一副中发白刻
	HU_SANYUANPAITWO=16,		    --二副中发白刻
	HU_FENGPAIKEQUAN=17,		    --风牌刻与圈相同
	HU_FENGPAIKEWEI=18,			    --风牌刻与位相同
    
	HU_DADANDIAO = 82,			    --大单吊
	HU_DANDIAO = 83,			    --单吊
	HU_HUBIAN = 84,				    --边
	HU_KAPAI = 85,				    --坎牌
	HU_BAOHU = 86,                  --未知
	HU_JIHU = 101,				    --鸡胡
	HU_PING = 102,				    --平胡
	HU_PENGPENGHU = 103,		    --碰碰胡
	HU_HUNYISE = 104,			    --混一色
	HU_HUNPENG = 105,			    --混碰
	HU_QINGPENG = 106,              --未知
	HU_HUNYAOJIU = 108,			    --混幺九
	HU_XIAOSANYUAN = 109,		    --小三元
	HU_XIAOSIXI = 110,			    --小四喜
	HU_ZIYISE = 111,			    --字一色
	HU_QINGYAOJIU = 112,		    --清幺九
	HU_DASANYUAN = 113,			    --大三元
	HU_DASIXI = 114,			    --大四喜
	HU_SHISANYAO = 115,			    --十三幺
	HU_RENHU = 118,				    --人胡
	HU_DIHU = 119,				    --地胡
	HU_TIANHU = 120,			    --天胡
	HU_JIULIANBAODENG = 121,	    --九莲宝灯
	HU_FOURGHOST = 122,			    --四鬼胡
	HU_YAOJIU = 123,			    --幺九
	HU_NOGHOST2TIMES = 124,		    --无鬼加番
    
	HU_FLOWERMATCHSINGLE = 125,	    --花吊单
	HU_FLOWERMATCHFLOWER = 126,     --花吊花
	HU_GENGZHUANGSUCC = 127,
	HU_GANG_QIANG = 129,    
	HU_GANG_FLOWER = 130,		    --杠上开花
	HU_YITIAOLONG = 131,		    --一条龙
	HU_LAOSHAO = 132,			    --老少
	HU_DALIAN = 133,			    --大连
	HU_XIAOLIAN = 134,			    --小连
	HU_DAGAO = 135,				    --大高
	HU_XIAOGAO = 136,			    --小高
	HU_BAZHANG = 137,			    --八张
	HU_QUEMEN = 138,			    --缺一门
	HU_SIGUIYI = 139,			    --四归一
	HU_ZHUO5 = 140,				    --捉五
    
	HU_QINGYISE = 142,			    --清一色
	HU_CAISHENHU = 143,			    --财神胡(+15)
	HU_CAISHENHU_TYPE = 144,	    --财神胡
	HU_MENQING_X2=145,			    --门清
	--HU_ANGANG=146,			    --暗杠
	--HU_MGANG=147,				    --明杠
	HU_ANKE=148,				    --暗刻
	    
	HU_CHENGHU=151,				    --成胡
	HU_HAOHUAQIDUIX2=152,		    --豪华x2
	--HU_JIEPAO =153,			    --接炮
	HU_DUN =154,				    --坐
	HU_LA  =155,					--拉
	HU_PAO =156,				    --跑
	--HU_LUXURYQIDUI_SHUANG = 157,   --双豪华七对
	HU_ZHAZHEN = 158,			     --扎针
	HU_ZHAZHEN_LOSE = 160,		     --扎针-fen
	HU_DAIZHUANG = 162,			     --带庄
	HU_DAIZHUANG_LOSE = 164,	     --带庄
	--HU_JIAHU = 163,			     --夹胡
	HU_LIANGXI_LOSE = 166,		     --亮喜+
	HU_LIANGXI_1 = 165,			     --亮喜x2
	HU_LIANGXI_2 = 167,			     --亮喜x4
	HU_LIANGXI_3 = 168,			     --亮喜x8
	HU_LIANGXI_4 = 169,			     --亮喜x16
	HU_DIANGANG=170,			     --点杠
	HU_JIEGANGANG=171,			     --接杠
	--HU_QIANGGANGHU_LOSE=172,	     --抢扛胡
	HU_BAOJIAO = 173,			     --报叫
	HU_PIAOFEN = 174,			     --飘分

	HU_QINGYISE_YITIAOLONG = 175,	 --清一色一条龙
	HU_QINGYISE_QIDUI = 176,		 --清一色七对
	HU_QINGYISE_HAOQI = 177,		 --清一色豪华七对
	HU_QINGYISE_PPH = 178,			 --清一色对对胡
	--安庆 增加
	HU_SHISANLAN = 179,				 --十三烂
	HU_QIXINGGUIWEI = 180,			 --七星归位(十三烂的一种)
	HU_DUIDAO = 181,				 --对倒胡
	HU_WUHUAGUO = 182,				 --无花果
	HU_SHUNSANKOU = 183,			 --顺三口
	HU_FANSANKOU = 184,				 --反三口
	HU_BUHUA = 185,					 --补花

	--淮北
	HU_SHISANBUKAO_X  = 186,		--十三不靠
	HU_XIAOHU_X       = 187,		--小胡
	HU_SHISANYAO_X    = 188,		--十三幺
	HU_QIDUI_X        = 189,		--七对
	HU_ZIMO_X         = 199,		--自摸
	HU_GANG_FLOWER_X  = 200,		--杠上开花
	HU_GANGSHANGPAO_X = 201,		--杠上炮
	HU_HUAIBEI_RATIO  = 202,		--系数,结算不显示系数二字
	HU_DUNLAPAO       = 203,		--坐后跑
	HU_GANGFEN        = 204,		--杠分
}

m.huTpyeStr = {
	[m.huTpye.HU_PINGHU				    ] = "平胡",
	[m.huTpye.HU_ZIMO				    ] = "自摸",
	[m.huTpye.HU_MENQING				] = "门清",
	[m.huTpye.HU_PIAOHU				    ] = "飘胡",
	[m.huTpye.HU_QIDUI 				    ] = "七对",
	[m.huTpye.HU_QIANGMINGGANGHU 		] = "抢明扛胡",
	[m.huTpye.HU_MOBAO 			        ] = "摸宝",
	[m.huTpye.HU_DIANPAO 			    ] = "点炮",
	[m.huTpye.HU_JIEPAO 				] = "接炮",
	[m.huTpye.HU_LUXURYQIDUI 		    ] = "豪华七对",
	[m.huTpye.HU_LUXURYQIDUI_SHUANG 	] = "双豪华七对",
	[m.huTpye.HU_ZHIZUNQIDUI 		    ] = "至尊豪华七对",
	[m.huTpye.HU_JIAHU 				    ] = "夹胡",
	[m.huTpye.HU_CHONGBAO 		        ] = "冲宝 听牌后有效",
	[m.huTpye.HU_TINGPAI 			    ] = "可听牌",
	[m.huTpye.HU_ANGANG                 ] = "暗杠",
	[m.huTpye.HU_MGANG                  ] = "明杠",
	[m.huTpye.HU_SPECIAL_MD             ] = "明大蛋",
	[m.huTpye.HU_SPECIAL_AD             ] = "暗大蛋",
	[m.huTpye.HU_WIN_KAIPAIZHA          ] = "开牌炸",
	[m.huTpye.HU_SHUNBAOHU              ] = "选择顺宝胡",
	[m.huTpye.HU_DIANPAO_X2			    ] = "点炮x2",
	[m.huTpye.HU_XIAOHU 				] = "胡牌分",
	[m.huTpye.HU_GANGSHANGPAO			] = "杠上炮",
	[m.huTpye.HU_HAIDILAO			    ] = "海底捞",
	[m.huTpye.HU_HAIDIPAO				] = "海底炮",
	[m.huTpye.HU_QISHOUFOURLAN		    ] = "起手四个赖子",
	[m.huTpye.HU_SANYUANPAIONE		    ] = "一副中发白刻",
	[m.huTpye.HU_SANYUANPAITWO		    ] = "二副中发白刻",
	[m.huTpye.HU_FENGPAIKEQUAN		    ] = "风牌刻与圈相同",
	[m.huTpye.HU_FENGPAIKEWEI			] = "风牌刻与位相同",
	[m.huTpye.HU_DADANDIAO			    ] = "大单吊",
	[m.huTpye.HU_DANDIAO			    ] = "单吊",
	[m.huTpye.HU_HUBIAN 				] = "边",
	[m.huTpye.HU_KAPAI				    ] = "坎牌",
	[m.huTpye.HU_BAOHU                  ] = "未知",
	[m.huTpye.HU_JIHU 				    ] = "鸡胡",
	[m.huTpye.HU_PING 				    ] = "平胡",
	[m.huTpye.HU_PENGPENGHU 		    ] = "碰碰胡",
	[m.huTpye.HU_HUNYISE 		        ] = "混一色",
	[m.huTpye.HU_HUNPENG 		        ] = "混碰",
	[m.huTpye.HU_QINGPENG               ] = "未知",
	[m.huTpye.HU_HUNYAOJIU 			    ] = "混幺九",
	[m.huTpye.HU_XIAOSANYUAN		    ] = "小三元",
	[m.huTpye.HU_XIAOSIXI 			    ] = "小四喜",
	[m.huTpye.HU_ZIYISE 			    ] = "字一色",
	[m.huTpye.HU_QINGYAOJIU 		    ] = "清幺九",
	[m.huTpye.HU_DASANYUAN 			    ] = "大三元",
	[m.huTpye.HU_DASIXI 			    ] = "大四喜",
	[m.huTpye.HU_SHISANYAO 			    ] = "十三幺",
	[m.huTpye.HU_RENHU 				    ] = "人胡",
	[m.huTpye.HU_DIHU 				    ] = "地胡",
	[m.huTpye.HU_TIANHU 			    ] = "天胡",
	[m.huTpye.HU_JIULIANBAODENG 	    ] = "九莲宝灯",
	[m.huTpye.HU_FOURGHOST 		        ] = "四鬼胡",
	[m.huTpye.HU_YAOJIU 			    ] = "幺九",
	[m.huTpye.HU_NOGHOST2TIMES 		    ] = "无鬼加番",
	[m.huTpye.HU_FLOWERMATCHSINGLE 	    ] = "花吊单",
	[m.huTpye.HU_FLOWERMATCHFLOWER      ] = "花吊花",
	[m.huTpye.HU_GANG_FLOWER		    ] = "杠上开花",
	[m.huTpye.HU_YITIAOLONG 	        ] = "一条龙",
	[m.huTpye.HU_LAOSHAO 			    ] = "老少",
	[m.huTpye.HU_DALIAN 		        ] = "大连",
	[m.huTpye.HU_XIAOLIAN			    ] = "小连",
	[m.huTpye.HU_DAGAO  			    ] = "大高",
	[m.huTpye.HU_XIAOGAO 			    ] = "小高",
	[m.huTpye.HU_BAZHANG 			    ] = "八张",
	[m.huTpye.HU_QUEMEN		            ] = "缺一门",
	[m.huTpye.HU_SIGUIYI 		        ] = "四归一",
	[m.huTpye.HU_ZHUO5 				    ] = "捉五",
	[m.huTpye.HU_QINGYISE 			    ] = "清一色",
	[m.huTpye.HU_CAISHENHU			    ] = "财神胡",
	[m.huTpye.HU_CAISHENHU_TYPE	        ] = "财神胡",
	[m.huTpye.HU_MENQING_X2			    ] = "门清",
	[m.huTpye.HU_ANKE				    ] = "暗刻",
	[m.huTpye.HU_CHENGHU				] = "成胡",
	[m.huTpye.HU_HAOHUAQIDUIX2	        ] = "豪华x2",
	[m.huTpye.HU_DUN				    ] = "坐",
	[m.huTpye.HU_LA					    ] = "拉",
	[m.huTpye.HU_PAO				    ] = "跑",
	[m.huTpye.HU_ZHAZHEN 		        ] = "扎针",
	[m.huTpye.HU_ZHAZHEN_LOSE		    ] = "扎针",
	[m.huTpye.HU_DAIZHUANG 			    ] = "带庄",
	[m.huTpye.HU_DAIZHUANG_LOSE 	    ] = "带庄",
	[m.huTpye.HU_LIANGXI_LOSE 		    ] = "亮喜+",
	[m.huTpye.HU_LIANGXI_1			    ] = "亮喜x2",
	[m.huTpye.HU_LIANGXI_2			    ] = "亮喜x4",
	[m.huTpye.HU_LIANGXI_3			    ] = "亮喜x8",
	[m.huTpye.HU_LIANGXI_4			    ] = "亮喜x16",
	[m.huTpye.HU_DIANGANG		        ] = "点杠",
	[m.huTpye.HU_JIEGANGANG			    ] = "接杠",
	[m.huTpye.HU_BAOJIAO		        ] = "报叫",
	[m.huTpye.HU_PIAOFEN		        ] = "飘分",
	[m.huTpye.HU_QINGYISE_YITIAOLONG	] = "清一色一条龙",
	[m.huTpye.HU_QINGYISE_QIDUI		    ] = "清一色七对",
	[m.huTpye.HU_QINGYISE_HAOQI		    ] = "清一色豪华七对",
	[m.huTpye.HU_QINGYISE_PPH	        ] = "清一色对对胡",
	[m.huTpye.HU_SHISANLAN 	            ] = "十三烂",
	[m.huTpye.HU_QIXINGGUIWEI	        ] = "七星归位",
	[m.huTpye.HU_DUIDAO 			    ] = "对倒胡",
	[m.huTpye.HU_WUHUAGUO 	            ] = "无花果",
	[m.huTpye.HU_SHUNSANKOU			    ] = "顺三口",
	[m.huTpye.HU_FANSANKOU 		        ] = "反三口",
	[m.huTpye.HU_BUHUA 			        ] = "补花",

	[m.huTpye.HU_SHISANBUKAO_X          ] = "十三不靠",
	[m.huTpye.HU_XIAOHU_X               ] = "小胡",
	[m.huTpye.HU_SHISANYAO_X            ] = "十三幺",
	[m.huTpye.HU_QIDUI_X                ] = "七对",
	[m.huTpye.HU_ZIMO_X                 ] = "自摸",
	[m.huTpye.HU_GANG_FLOWER_X          ] = "杠上开花",
	[m.huTpye.HU_GANGSHANGPAO_X         ] = "杠上炮",
	[m.huTpye.HU_HUAIBEI_RATIO          ] = "",
	[m.huTpye.HU_DUNLAPAO               ] = "坐后跑",
	[m.huTpye.HU_GANGFEN                ] = "杠分",
}


return m
